services:
  backend:
    image: ghcr.io/erikk4/simtune-backend:latest
    container_name: simtune-backend
    ports:
      - "8081:8080"

  frontend:
    image: ghcr.io/erikk4/simtune-frontend:latest
    container_name: simtune-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  adminer: 
    image: ghcr.io/erikk4/simtune-adminer:latest
    container_name: simtune-adminer
    ports:
      - "8082:80"
    depends_on:
      - backend
